[project]
name = "hdoc"
version = "1.4.0"
git_repo_url = "https://github.com/hdoc/hdoc/"
git_default_branch = "master"

[paths]
compile_commands = "build/compile_commands.json"
output_dir = "hdoc-output"

[includes]
paths = []
use_system_includes = true

[ignore]
paths = [
  "/tests/",
  "/subprojects/",
]

[pages]
homepage = "README.md"
